package com.quietdose.brain.analysis

/**
 * A curated, authoritative knowledge base of well-established NON-supplement items —
 * the validated ground-truth backbone that gives skincare, devices, haircare and
 * functional foods the same trusted base that [IngredientCatalog] gives supplements.
 *
 * Each entry is a [CategoryProfile] encoded conservatively from common, undisputed
 * references. The [StackAnalyzer] / [ProfileSkill] consult this FIRST; the on-device
 * model only fills gaps or covers unknown products — the curated facts win. Hedged by
 * construction, never medical advice, and no invented numbers: [recommendedAmount]/
 * [recommendedUnit] are set ONLY where there is a genuine standard (a serum "2 drops",
 * sunscreen "two-finger"); otherwise the amount is null and guidance lives in [usage].
 *
 * Matching mirrors [IngredientCatalog.match] — exact alias first, then longest-alias
 * containment — via the per-entry [Curated.aliases].
 *
 * Current coverage (starter batch):
 *   - Skincare:         41   (target ~200  → ~159 remaining)
 *   - Devices:          12   (target ~25   → ~13 remaining)
 *   - Haircare:         12   (target ~25   → ~13 remaining)
 *   - Functional foods: 13   (target ~25   → ~12 remaining)
 */
object CuratedProfiles {

    /** A curated profile plus the label spellings used to match it. */
    private data class Curated(val aliases: List<String>, val profile: CategoryProfile)

    private fun skincare(
        aliases: List<String>,
        categoryLabel: String,
        whatItIs: String,
        goodFor: List<String> = emptyList(),
        fitsWho: List<String> = emptyList(),
        usage: String = "",
        routineStep: String = "",
        recommendedAmount: Double? = null,
        recommendedUnit: String? = null,
        absorption: String = "",
        safety: List<String> = emptyList(),
        dontCombine: List<String> = emptyList(),
        verify: List<String> = emptyList(),
        confidence: Int = 85,
    ) = Curated(
        aliases,
        CategoryProfile(
            kind = ItemKind.SKINCARE, categoryLabel = categoryLabel, whatItIs = whatItIs,
            goodFor = goodFor, fitsWho = fitsWho, usage = usage, routineStep = routineStep,
            recommendedAmount = recommendedAmount, recommendedUnit = recommendedUnit,
            absorption = absorption, safety = safety, dontCombine = dontCombine,
            verify = verify, confidence = confidence,
        ),
    )

    private fun haircare(
        aliases: List<String>,
        categoryLabel: String,
        whatItIs: String,
        goodFor: List<String> = emptyList(),
        fitsWho: List<String> = emptyList(),
        usage: String = "",
        routineStep: String = "",
        recommendedAmount: Double? = null,
        recommendedUnit: String? = null,
        absorption: String = "",
        safety: List<String> = emptyList(),
        dontCombine: List<String> = emptyList(),
        verify: List<String> = emptyList(),
        confidence: Int = 85,
    ) = Curated(
        aliases,
        CategoryProfile(
            kind = ItemKind.HAIRCARE, categoryLabel = categoryLabel, whatItIs = whatItIs,
            goodFor = goodFor, fitsWho = fitsWho, usage = usage, routineStep = routineStep,
            recommendedAmount = recommendedAmount, recommendedUnit = recommendedUnit,
            absorption = absorption, safety = safety, dontCombine = dontCombine,
            verify = verify, confidence = confidence,
        ),
    )

    private fun device(
        aliases: List<String>,
        categoryLabel: String,
        whatItIs: String,
        goodFor: List<String> = emptyList(),
        fitsWho: List<String> = emptyList(),
        usage: String = "",
        routineStep: String = "",
        absorption: String = "",
        safety: List<String> = emptyList(),
        dontCombine: List<String> = emptyList(),
        verify: List<String> = emptyList(),
        confidence: Int = 85,
    ) = Curated(
        aliases,
        CategoryProfile(
            kind = ItemKind.DEVICE, categoryLabel = categoryLabel, whatItIs = whatItIs,
            goodFor = goodFor, fitsWho = fitsWho, usage = usage, routineStep = routineStep,
            absorption = absorption, safety = safety, dontCombine = dontCombine,
            verify = verify, confidence = confidence,
        ),
    )

    private fun food(
        aliases: List<String>,
        categoryLabel: String,
        whatItIs: String,
        goodFor: List<String> = emptyList(),
        fitsWho: List<String> = emptyList(),
        usage: String = "",
        routineStep: String = "",
        recommendedAmount: Double? = null,
        recommendedUnit: String? = null,
        absorption: String = "",
        safety: List<String> = emptyList(),
        dontCombine: List<String> = emptyList(),
        verify: List<String> = emptyList(),
        confidence: Int = 85,
    ) = Curated(
        aliases,
        CategoryProfile(
            kind = ItemKind.FOOD, categoryLabel = categoryLabel, whatItIs = whatItIs,
            goodFor = goodFor, fitsWho = fitsWho, usage = usage, routineStep = routineStep,
            recommendedAmount = recommendedAmount, recommendedUnit = recommendedUnit,
            absorption = absorption, safety = safety, dontCombine = dontCombine,
            verify = verify, confidence = confidence,
        ),
    )

    // ====================================================================== //
    //  SKINCARE — ~40 well-established actives/products                      //
    // ====================================================================== //
    private val SKINCARE = listOf(
        skincare(
            aliases = listOf("niacinamide", "vitamin b3 serum", "nicotinamide serum"),
            categoryLabel = "Niacinamide serum",
            whatItIs = "A water-based form of vitamin B3 used to calm skin and even out tone.",
            goodFor = listOf("Reducing the look of pores", "Balancing oil", "Evening out tone and redness", "Supporting the skin barrier"),
            fitsWho = listOf("Suits most skin types, including oily and sensitive", "A gentle entry-level active"),
            usage = "Apply a thin layer AM and/or PM after cleansing, before heavier creams. Daily use is fine.",
            routineStep = "After cleansing/toner, before moisturiser; AM and/or PM",
            recommendedAmount = 3.0, recommendedUnit = "drops",
            absorption = "Water-soluble; sinks into damp skin quickly. Layer it under your moisturiser.",
            safety = listOf("Generally well tolerated; very high concentrations can cause flushing in some people"),
            dontCombine = listOf("Strong acids in the same layer (space them out if your skin is sensitive)"),
            verify = listOf("Check the concentration on the label", "Patch test if your skin is reactive"),
        ),
        skincare(
            aliases = listOf("retinol", "retinoid", "retinaldehyde", "retinal serum"),
            categoryLabel = "Retinol / retinoid",
            whatItIs = "A vitamin A derivative that speeds skin renewal — a leading anti-ageing active.",
            goodFor = listOf("Fine lines and texture", "Acne and clogged pores", "Overall renewal and tone"),
            fitsWho = listOf("Best started slowly", "Not for use in pregnancy", "Sensitive skin should ease in"),
            usage = "PM only, on dry skin, 2–3 nights a week to start, building up as tolerated. Always wear sunscreen the next day.",
            routineStep = "PM only, after cleansing on dry skin, before moisturiser",
            recommendedAmount = 1.0, recommendedUnit = "pea-size",
            absorption = "Penetrates to where skin cells turn over; effects build over weeks, not days.",
            safety = listOf("Avoid in pregnancy and breastfeeding", "Expect some initial dryness and flaking", "Increases sun sensitivity — daily SPF is essential"),
            dontCombine = listOf("AHA/BHA exfoliating acids in the same routine", "Benzoyl peroxide at the same time", "Vitamin C in the same layer (split AM/PM)"),
            verify = listOf("Start low and slow", "Patch test first", "Pair with daily sunscreen"),
        ),
        skincare(
            aliases = listOf("tretinoin", "retin-a", "retin a"),
            categoryLabel = "Tretinoin (prescription retinoid)",
            whatItIs = "A prescription-strength retinoid for acne and ageing — stronger than over-the-counter retinol.",
            goodFor = listOf("Acne", "Fine lines and texture", "Tone"),
            fitsWho = listOf("Used under medical guidance", "Not for use in pregnancy"),
            usage = "PM only, on dry skin, as directed by your prescriber. Build frequency slowly; daily sunscreen is essential.",
            recommendedAmount = 1.0, recommendedUnit = "pea-size",
            absorption = "Potent renewal active; results build over weeks.",
            safety = listOf("Prescription item — follow your clinician's guidance", "Avoid in pregnancy", "Strong sun sensitivity"),
            dontCombine = listOf("AHA/BHA acids", "Benzoyl peroxide at the same time", "Other retinoids"),
            verify = listOf("Use exactly as prescribed", "Daily SPF"),
        ),
        skincare(
            aliases = listOf("adapalene", "differin"),
            categoryLabel = "Adapalene (retinoid)",
            whatItIs = "A stable retinoid widely used for acne, available over the counter in many places.",
            goodFor = listOf("Acne and clogged pores", "Texture"),
            fitsWho = listOf("Acne-prone skin", "Not for use in pregnancy"),
            usage = "PM only, a thin layer over the whole area, building up frequency. Daily sunscreen.",
            recommendedAmount = 1.0, recommendedUnit = "pea-size",
            absorption = "Targets the pore lining; effects build over several weeks.",
            safety = listOf("Avoid in pregnancy", "Expect a purge/dry phase early on", "Sun sensitivity"),
            dontCombine = listOf("AHA/BHA acids in the same routine", "Benzoyl peroxide at the same time"),
            verify = listOf("Give it 8–12 weeks", "Daily SPF"),
        ),
        skincare(
            aliases = listOf("bakuchiol"),
            categoryLabel = "Bakuchiol serum",
            whatItIs = "A plant-derived ingredient marketed as a gentler retinol alternative.",
            goodFor = listOf("Fine lines and tone", "A retinol-style effect with less irritation"),
            fitsWho = listOf("Sensitive skin", "Those who can't tolerate retinol"),
            usage = "AM or PM after cleansing. Daily use is fine.",
            absorption = "Oil-soluble; layers under moisturiser.",
            safety = listOf("Generally gentle; patch test if reactive"),
            verify = listOf("Evidence is younger than retinol's — manage expectations"),
        ),
        skincare(
            aliases = listOf("vitamin c serum", "vitamin c", "ascorbic acid", "ascorbate", "l-ascorbic"),
            categoryLabel = "Vitamin C serum",
            whatItIs = "An antioxidant serum that brightens tone and helps defend against daily damage.",
            goodFor = listOf("Brightening dull skin", "Evening out tone and dark spots", "Antioxidant defence under sunscreen"),
            fitsWho = listOf("Most skin types", "Sensitive skin should start at a lower strength"),
            usage = "AM after cleansing, before moisturiser and sunscreen. Daily.",
            routineStep = "AM, after cleansing/toner, before moisturiser and sunscreen",
            recommendedAmount = 3.0, recommendedUnit = "drops",
            absorption = "Works best at a low pH; pure forms oxidise over time — store cool and dark.",
            safety = listOf("Can sting or tingle on sensitive skin", "Discontinue if it turns dark orange (oxidised)"),
            dontCombine = listOf("Strong acids and retinol in the same layer — space them (e.g. vitamin C AM, retinol PM)"),
            verify = listOf("Check it's not oxidised", "Patch test", "Keep it sealed and cool"),
        ),
        skincare(
            aliases = listOf("hyaluronic acid", "hyaluronic", "ha serum", "sodium hyaluronate"),
            categoryLabel = "Hyaluronic acid serum",
            whatItIs = "A humectant that draws water into the skin for a plumper, hydrated look.",
            goodFor = listOf("Hydration and plumpness", "Smoothing the look of fine lines"),
            fitsWho = listOf("All skin types, including oily", "Especially dehydrated skin"),
            usage = "Apply to damp skin AM and/or PM, then seal with moisturiser. Daily.",
            routineStep = "After cleansing/toner on damp skin, before moisturiser; AM and/or PM",
            recommendedAmount = 3.0, recommendedUnit = "drops",
            absorption = "Holds water at the surface; needs a moisturiser on top in dry climates or it can pull moisture from skin.",
            safety = listOf("Very well tolerated"),
            verify = listOf("Apply to damp skin and seal it in"),
        ),
        skincare(
            aliases = listOf("salicylic acid", "bha", "beta hydroxy"),
            categoryLabel = "Salicylic acid (BHA)",
            whatItIs = "An oil-soluble exfoliating acid that clears pores from the inside.",
            goodFor = listOf("Blackheads and clogged pores", "Oily, acne-prone skin", "Smoothing texture"),
            fitsWho = listOf("Oily and acne-prone skin", "Use sparingly on dry or sensitive skin"),
            usage = "PM (or AM) a few times a week, after cleansing, before moisturiser. Build up slowly.",
            absorption = "Oil-soluble, so it gets into pores; over-use strips the barrier.",
            safety = listOf("Can dry or irritate with overuse", "Increases sun sensitivity"),
            dontCombine = listOf("Retinol in the same routine", "Other exfoliating acids at once", "Benzoyl peroxide at the same time"),
            verify = listOf("Start a few times a week", "Daily SPF"),
        ),
        skincare(
            aliases = listOf("glycolic acid", "aha", "alpha hydroxy", "glycolic"),
            categoryLabel = "Glycolic acid (AHA)",
            whatItIs = "A small alpha-hydroxy acid that exfoliates the surface for brighter, smoother skin.",
            goodFor = listOf("Dullness and uneven texture", "Tone and mild dark spots"),
            fitsWho = listOf("Normal to resilient skin", "Sensitive skin should choose a gentler acid like lactic"),
            usage = "PM a few nights a week, after cleansing. Build up slowly; daily sunscreen is essential.",
            absorption = "Penetrates the surface layers; the smallest AHA, so among the strongest.",
            safety = listOf("Can sting and increase sun sensitivity", "Easy to overdo"),
            dontCombine = listOf("Retinol in the same routine", "Other acids at once", "Vitamin C in the same layer"),
            verify = listOf("Start low frequency", "Daily SPF"),
        ),
        skincare(
            aliases = listOf("lactic acid"),
            categoryLabel = "Lactic acid (AHA)",
            whatItIs = "A gentler alpha-hydroxy acid that exfoliates while also hydrating.",
            goodFor = listOf("Gentle brightening and smoothing", "Dry or sensitive skin that wants exfoliation"),
            fitsWho = listOf("Dry and sensitive skin", "AHA beginners"),
            usage = "PM a few nights a week after cleansing. Daily sunscreen.",
            absorption = "Larger than glycolic, so it works more on the surface and is milder.",
            safety = listOf("Milder than glycolic but still raises sun sensitivity"),
            dontCombine = listOf("Retinol in the same routine", "Other acids at once"),
            verify = listOf("Daily SPF"),
        ),
        skincare(
            aliases = listOf("mandelic acid"),
            categoryLabel = "Mandelic acid (AHA)",
            whatItIs = "A large-molecule AHA that exfoliates gently — well suited to sensitive and darker skin.",
            goodFor = listOf("Gentle exfoliation", "Tone and mild breakouts"),
            fitsWho = listOf("Sensitive skin", "Darker skin tones prone to marks"),
            usage = "PM a few nights a week. Daily sunscreen.",
            absorption = "The large molecule penetrates slowly, making it one of the gentler acids.",
            safety = listOf("Gentle, but still increases sun sensitivity"),
            dontCombine = listOf("Retinol in the same routine", "Other acids at once"),
            verify = listOf("Daily SPF"),
        ),
        skincare(
            aliases = listOf("azelaic acid", "azelaic"),
            categoryLabel = "Azelaic acid",
            whatItIs = "A multi-tasking acid that calms redness, fades marks and helps with breakouts.",
            goodFor = listOf("Redness and rosacea-prone skin", "Post-acne marks", "Breakouts"),
            fitsWho = listOf("Sensitive and redness-prone skin", "Often considered safe in pregnancy — confirm with your clinician"),
            usage = "AM and/or PM, a thin layer after cleansing. Daily use is fine.",
            absorption = "Gentle on the barrier; results build over weeks.",
            safety = listOf("May cause mild tingling at first", "Generally well tolerated"),
            verify = listOf("Give it several weeks", "Confirm pregnancy use with a clinician"),
        ),
        skincare(
            aliases = listOf("benzoyl peroxide", "bpo"),
            categoryLabel = "Benzoyl peroxide",
            whatItIs = "An anti-bacterial active that targets the bacteria behind acne.",
            goodFor = listOf("Inflammatory acne and spots"),
            fitsWho = listOf("Acne-prone skin", "Drier skin should use it sparingly"),
            usage = "Apply to affected areas, starting once daily or less. Can be drying.",
            absorption = "Works on the skin surface and in pores; can bleach fabric and towels.",
            safety = listOf("Drying and can irritate", "Bleaches coloured fabric and hair"),
            dontCombine = listOf("Retinoids at the same time of day", "Strong acids at once"),
            verify = listOf("Start low strength", "Use white towels"),
        ),
        skincare(
            aliases = listOf("ceramide", "ceramides"),
            categoryLabel = "Ceramide moisturiser",
            whatItIs = "Skin-identical lipids that rebuild and reinforce the moisture barrier.",
            goodFor = listOf("Repairing a damaged or dry barrier", "Locking in hydration", "Calming sensitivity"),
            fitsWho = listOf("All skin types", "Especially dry, sensitive or over-exfoliated skin"),
            usage = "AM and PM as your moisturiser step, over serums. Daily.",
            absorption = "Sit in the upper layers to seal moisture in and reinforce the barrier.",
            safety = listOf("Very well tolerated"),
            verify = listOf("Pair with gentler routines if your barrier is stressed"),
        ),
        skincare(
            aliases = listOf("peptide", "peptides", "matrixyl", "copper peptide"),
            categoryLabel = "Peptide serum",
            whatItIs = "Short chains of amino acids used to support firmness and a smoother look.",
            goodFor = listOf("Supporting firmness", "Smoothing fine lines", "Barrier support"),
            fitsWho = listOf("All skin types", "A gentle anti-ageing option"),
            usage = "AM and/or PM after lighter serums, before moisturiser. Daily.",
            routineStep = "After lighter serums, before moisturiser; AM and/or PM",
            absorption = "Work gradually; results are subtle and build over time.",
            safety = listOf("Generally gentle and well tolerated"),
            verify = listOf("Manage expectations — effects are gradual"),
        ),
        skincare(
            aliases = listOf("centella", "cica", "centella asiatica", "madecassoside", "tiger grass"),
            categoryLabel = "Centella (cica) serum",
            whatItIs = "A soothing botanical extract used to calm and support stressed skin.",
            goodFor = listOf("Calming redness and irritation", "Supporting the barrier", "Soothing after actives"),
            fitsWho = listOf("Sensitive, reactive or compromised skin"),
            usage = "AM and/or PM after cleansing. Daily; useful alongside strong actives to soothe.",
            absorption = "Lightweight; layers easily under moisturiser.",
            safety = listOf("Very gentle and well tolerated"),
            verify = listOf("Good buffer when using retinoids or acids"),
        ),
        skincare(
            aliases = listOf("zinc oxide", "zinc cream", "zinc pyrithione"),
            categoryLabel = "Zinc (topical)",
            whatItIs = "A mineral used in skincare to calm, protect and, in sunscreens, block UV.",
            goodFor = listOf("Calming irritation", "Oil control", "Physical sun protection (zinc oxide)"),
            fitsWho = listOf("Sensitive and acne-prone skin"),
            usage = "Use as directed for the specific product (sunscreen, cream or spot treatment).",
            absorption = "Sits on the surface; mineral sunscreen forms a physical barrier.",
            safety = listOf("Generally gentle", "Mineral sunscreens can leave a white cast"),
            verify = listOf("Check whether it's a sunscreen or a treatment"),
        ),
        skincare(
            aliases = listOf("sunscreen", "spf", "sunblock", "uv filter"),
            categoryLabel = "Sunscreen (SPF)",
            whatItIs = "The single most important step for protecting skin from UV damage and ageing.",
            goodFor = listOf("Preventing sun damage and burning", "Slowing visible ageing", "Protecting after actives like retinol or acids"),
            fitsWho = listOf("Everyone, every day", "Reapply when outdoors"),
            usage = "AM, the last skincare step, every day. Reapply every couple of hours in strong sun.",
            routineStep = "Last step, AM — over moisturiser, before makeup",
            recommendedAmount = 1.0, recommendedUnit = "two-finger",
            absorption = "Forms a protective film — apply generously; under-applying lowers the real protection a lot.",
            safety = listOf("Some filters can sting eyes", "Patch test if sensitive"),
            verify = listOf("Apply enough (about two fingers for the face)", "Reapply through the day"),
        ),
        skincare(
            aliases = listOf("squalane", "squalene"),
            categoryLabel = "Squalane oil",
            whatItIs = "A lightweight, skin-mimicking oil that softens and seals in moisture.",
            goodFor = listOf("Softening and sealing hydration", "Reducing trans-water loss"),
            fitsWho = listOf("Most skin types, including oily", "Lightweight and non-greasy"),
            usage = "PM (or AM) as the last step or mixed into moisturiser. A few drops.",
            routineStep = "Last step, over moisturiser (under sunscreen if AM)",
            recommendedAmount = 3.0, recommendedUnit = "drops",
            absorption = "Mimics the skin's own oils; absorbs without a heavy feel.",
            safety = listOf("Very well tolerated and non-comedogenic for most"),
            verify = listOf("Apply over water-based serums to seal them"),
        ),
        skincare(
            aliases = listOf("snail mucin", "snail secretion", "snail essence"),
            categoryLabel = "Snail mucin essence",
            whatItIs = "A hydrating, repairing essence popular in Korean skincare.",
            goodFor = listOf("Hydration and bounce", "Supporting repair", "Calming"),
            fitsWho = listOf("Most skin types", "Those wanting lightweight hydration"),
            usage = "AM and/or PM after cleansing, before moisturiser. Daily.",
            absorption = "Lightweight and layers well; sinks in quickly.",
            safety = listOf("Generally gentle; patch test if you have allergies"),
            verify = listOf("Patch test if prone to reactions"),
        ),
        skincare(
            aliases = listOf("tranexamic acid"),
            categoryLabel = "Tranexamic acid serum",
            whatItIs = "An active used to fade stubborn discolouration and even out tone.",
            goodFor = listOf("Dark spots and melasma-type discolouration", "Evening tone"),
            fitsWho = listOf("Skin with stubborn pigmentation", "Often paired with niacinamide or vitamin C"),
            usage = "AM and/or PM after cleansing. Daily; pair with sunscreen for best results.",
            absorption = "Works gradually on pigment pathways; results build over weeks.",
            safety = listOf("Generally well tolerated topically"),
            verify = listOf("Daily SPF is key for pigmentation", "Give it several weeks"),
        ),
        skincare(
            aliases = listOf("alpha arbutin", "arbutin"),
            categoryLabel = "Alpha arbutin serum",
            whatItIs = "A gentle brightening active that helps fade dark spots.",
            goodFor = listOf("Dark spots and uneven tone"),
            fitsWho = listOf("Most skin types", "A gentle option for pigmentation"),
            usage = "AM and/or PM after cleansing. Daily, with sunscreen.",
            absorption = "Works gradually; pairs well with vitamin C and niacinamide.",
            safety = listOf("Gentle and well tolerated"),
            verify = listOf("Daily SPF", "Be patient — pigment fades slowly"),
        ),
        skincare(
            aliases = listOf("kojic acid"),
            categoryLabel = "Kojic acid",
            whatItIs = "A brightening active used to fade pigmentation.",
            goodFor = listOf("Dark spots and uneven tone"),
            fitsWho = listOf("Skin with discolouration", "Sensitive skin should patch test"),
            usage = "Use as directed, usually PM, with daily sunscreen.",
            absorption = "Works on pigment over time.",
            safety = listOf("Can irritate sensitive skin", "Raises sun sensitivity"),
            verify = listOf("Patch test", "Daily SPF"),
        ),
        skincare(
            aliases = listOf("panthenol", "provitamin b5", "vitamin b5 serum"),
            categoryLabel = "Panthenol (B5)",
            whatItIs = "A soothing humectant that hydrates and supports the barrier.",
            goodFor = listOf("Hydration", "Calming and supporting repair"),
            fitsWho = listOf("All skin types, including sensitive"),
            usage = "AM and/or PM; common in essences and moisturisers. Daily.",
            absorption = "Lightweight humectant; layers easily.",
            safety = listOf("Very gentle"),
        ),
        skincare(
            aliases = listOf("allantoin"),
            categoryLabel = "Allantoin",
            whatItIs = "A soothing ingredient that calms and softens skin.",
            goodFor = listOf("Calming irritation", "Softening rough skin"),
            fitsWho = listOf("Sensitive skin"),
            usage = "Common as a supporting ingredient; use the product as directed.",
            absorption = "Gentle surface conditioner.",
            safety = listOf("Very well tolerated"),
        ),
        skincare(
            aliases = listOf("rosehip oil", "rosehip"),
            categoryLabel = "Rosehip oil",
            whatItIs = "A nourishing facial oil rich in fatty acids, used for tone and softness.",
            goodFor = listOf("Softening and nourishing", "Supporting tone over time"),
            fitsWho = listOf("Dry and normal skin", "Oily skin should use sparingly"),
            usage = "PM as the last step or mixed into moisturiser. A few drops.",
            recommendedAmount = 3.0, recommendedUnit = "drops",
            absorption = "An oil — apply over water-based products to seal them in.",
            safety = listOf("Generally gentle; can feel heavy on oily skin"),
        ),
        skincare(
            aliases = listOf("clay mask", "kaolin", "bentonite"),
            categoryLabel = "Clay mask",
            whatItIs = "A clarifying mask that absorbs excess oil and helps decongest pores.",
            goodFor = listOf("Oily and congested skin", "Temporarily reducing shine"),
            fitsWho = listOf("Oily and combination skin", "Dry skin should use sparingly"),
            usage = "PM, once or twice a week. Don't let it fully dry out and crack — rinse while still tacky.",
            absorption = "Draws oil from the surface; over-use can leave skin tight and dry.",
            safety = listOf("Can over-dry if left on too long or used too often"),
            verify = listOf("Limit to once or twice weekly"),
        ),
        skincare(
            aliases = listOf("micellar water", "micellar"),
            categoryLabel = "Micellar water",
            whatItIs = "A gentle, rinse-free cleanser that lifts makeup and grime.",
            goodFor = listOf("Quick cleansing and makeup removal"),
            fitsWho = listOf("All skin types", "Handy for travel or mornings"),
            usage = "On a cotton pad to wipe skin; follow with a proper cleanse for heavier makeup.",
            absorption = "Surfactant micelles lift oil and dirt off the surface.",
            safety = listOf("Gentle; rinse off if it leaves residue"),
        ),
        skincare(
            aliases = listOf("cleanser", "face wash", "facewash", "gel cleanser", "foaming cleanser"),
            categoryLabel = "Facial cleanser",
            whatItIs = "The first step that removes oil, dirt and product without stripping the skin.",
            goodFor = listOf("Clean skin as a base for the rest of the routine"),
            fitsWho = listOf("Everyone", "Choose gentle for dry/sensitive, gel/foaming for oily"),
            usage = "AM and PM; massage in and rinse. Skin should feel clean, not tight.",
            routineStep = "First step, AM and PM (after cleansing oil at night)",
            absorption = "Rinse-off; a stripped, squeaky feel means it's too harsh.",
            safety = listOf("Avoid over-cleansing, which damages the barrier"),
            verify = listOf("If skin feels tight after, switch to a gentler one"),
        ),
        skincare(
            aliases = listOf("cleansing oil", "cleansing balm", "double cleanse"),
            categoryLabel = "Cleansing oil / balm",
            whatItIs = "An oil-based first cleanse that melts away sunscreen and makeup.",
            goodFor = listOf("Removing sunscreen and makeup", "The first step of a double cleanse"),
            fitsWho = listOf("Anyone wearing sunscreen or makeup"),
            usage = "PM, massage onto dry skin, emulsify with water, then follow with a water-based cleanser.",
            routineStep = "First step, PM — before your water-based cleanser (double cleanse)",
            absorption = "Oil dissolves oil-based grime that water can't.",
            safety = listOf("Rinse well; follow with a second cleanse"),
        ),
        skincare(
            aliases = listOf("toner", "hydrating toner", "rice toner"),
            categoryLabel = "Toner",
            whatItIs = "A liquid step that hydrates or preps skin after cleansing.",
            goodFor = listOf("Adding light hydration", "Prepping skin for serums"),
            fitsWho = listOf("Most skin types", "Avoid harsh alcohol-based toners on dry skin"),
            usage = "AM and/or PM after cleansing, before serums. Pat in with hands.",
            routineStep = "After cleansing, before serums/essence; AM and/or PM",
            absorption = "Lightweight; preps the skin to receive what follows.",
            safety = listOf("Avoid stripping, high-alcohol formulas if dry or sensitive"),
        ),
        skincare(
            aliases = listOf("essence"),
            categoryLabel = "Essence",
            whatItIs = "A lightweight hydrating layer between toner and serum.",
            goodFor = listOf("Layered hydration", "Prepping skin"),
            fitsWho = listOf("Most skin types", "Popular in Korean routines"),
            usage = "AM and/or PM after toner, before serum. Pat in.",
            routineStep = "After toner, before serum; AM and/or PM",
            absorption = "Thin and fast-absorbing.",
            safety = listOf("Generally gentle"),
        ),
        skincare(
            aliases = listOf("moisturiser", "moisturizer", "face cream", "day cream", "night cream"),
            categoryLabel = "Moisturiser",
            whatItIs = "The step that hydrates and seals the barrier so skin stays comfortable.",
            goodFor = listOf("Hydration", "Sealing in serums", "Supporting the barrier"),
            fitsWho = listOf("Everyone", "Lighter gels for oily skin, richer creams for dry"),
            usage = "AM and PM as one of the final steps, over serums. Under sunscreen in the morning.",
            routineStep = "Near-last step, over serums; under sunscreen in the AM",
            absorption = "Forms a soft seal over actives to hold moisture in.",
            safety = listOf("Choose non-comedogenic if acne-prone"),
        ),
        skincare(
            aliases = listOf("eye cream"),
            categoryLabel = "Eye cream",
            whatItIs = "A gentle moisturiser formulated for the delicate eye area.",
            goodFor = listOf("Hydrating the under-eye", "Softening the look of fine lines"),
            fitsWho = listOf("Most people", "Optional if your face moisturiser is gentle enough"),
            usage = "AM and/or PM, a small amount patted gently around the orbital bone.",
            routineStep = "After serums, before/with moisturiser; AM and/or PM",
            recommendedAmount = 1.0, recommendedUnit = "rice-grain",
            absorption = "Lightweight; the thin eye skin absorbs little, so use a small amount.",
            safety = listOf("Keep out of the eyes", "Avoid strong actives here unless designed for it"),
        ),
        skincare(
            aliases = listOf("sheet mask", "face mask"),
            categoryLabel = "Sheet mask",
            whatItIs = "A single-use mask that delivers a hydrating or soothing boost.",
            goodFor = listOf("A short hydration or soothing boost"),
            fitsWho = listOf("Most skin types", "An occasional treat, not a daily essential"),
            usage = "Apply for the time on the pack, then pat in the leftover essence and moisturise.",
            absorption = "Seals serum against skin briefly; benefits are mostly short-term hydration.",
            safety = listOf("Don't leave on longer than directed — it can dry skin as it evaporates"),
        ),
        skincare(
            aliases = listOf("spot treatment", "acne patch", "pimple patch"),
            categoryLabel = "Spot treatment",
            whatItIs = "A targeted treatment for individual blemishes.",
            goodFor = listOf("Calming individual spots"),
            fitsWho = listOf("Occasional breakouts"),
            usage = "Apply only to the spot, as directed. Patches can be worn overnight.",
            absorption = "Concentrated on one area; avoid spreading actives over clear skin.",
            safety = listOf("Can dry the surrounding skin if overused"),
        ),
        skincare(
            aliases = listOf("face mist", "facial mist", "setting spray"),
            categoryLabel = "Face mist",
            whatItIs = "A spray for a quick refresh or light hydration through the day.",
            goodFor = listOf("A midday refresh", "Light hydration"),
            fitsWho = listOf("Most skin types"),
            usage = "Spritz as needed; pat in and follow with moisturiser if it's purely water.",
            absorption = "Surface-level; a plain water mist can dry skin as it evaporates unless sealed.",
            safety = listOf("Seal with moisturiser so it doesn't dry skin out"),
        ),
        skincare(
            aliases = listOf("retinol eye cream", "exfoliating peel", "peel pad", "exfoliant"),
            categoryLabel = "Exfoliating treatment",
            whatItIs = "A leave-on or wipe-off treatment that removes dead surface cells.",
            goodFor = listOf("Smoothing texture", "Brightening dullness"),
            fitsWho = listOf("Resilient skin", "Sensitive skin should go gentle and infrequent"),
            usage = "PM, a few times a week at most. Daily sunscreen afterwards.",
            absorption = "Loosens surface cells; over-use damages the barrier.",
            safety = listOf("Easy to over-exfoliate — watch for tightness or stinging", "Raises sun sensitivity"),
            dontCombine = listOf("Retinol in the same routine", "Stacking multiple acids"),
            verify = listOf("Limit frequency", "Daily SPF"),
        ),
        skincare(
            aliases = listOf("primer", "makeup primer"),
            categoryLabel = "Primer",
            whatItIs = "A base layer that smooths skin and helps makeup last.",
            goodFor = listOf("A smoother makeup base", "Helping makeup wear"),
            fitsWho = listOf("Makeup wearers"),
            usage = "AM after skincare and sunscreen, before makeup.",
            routineStep = "After sunscreen, before makeup; AM",
            absorption = "Sits on the surface as a grip layer.",
            safety = listOf("Choose non-comedogenic if acne-prone"),
        ),
        skincare(
            aliases = listOf("lip balm", "lip mask"),
            categoryLabel = "Lip balm",
            whatItIs = "An occlusive balm that protects and softens lips.",
            goodFor = listOf("Soothing dry, chapped lips"),
            fitsWho = listOf("Everyone, especially in cold or dry weather"),
            usage = "Apply as needed through the day and before bed.",
            absorption = "Forms a protective seal over the lips.",
            safety = listOf("Avoid known irritant flavours/fragrances if your lips react"),
        ),
        skincare(
            aliases = listOf("tinted moisturiser", "bb cream", "cc cream"),
            categoryLabel = "Tinted moisturiser / BB cream",
            whatItIs = "A light hybrid of moisturiser and coverage.",
            goodFor = listOf("Light, even coverage", "A simple base step"),
            fitsWho = listOf("Those wanting minimal makeup"),
            usage = "AM after skincare; if it contains SPF, still apply dedicated sunscreen for full protection.",
            absorption = "Surface tint plus light hydration.",
            safety = listOf("Built-in SPF is usually under-applied — use separate sunscreen too"),
            verify = listOf("Don't rely on its SPF alone"),
        ),
    )

    // ====================================================================== //
    //  DEVICES — ~12 common at-home tools                                    //
    // ====================================================================== //
    private val DEVICES = listOf(
        device(
            aliases = listOf("led mask", "led face mask", "light therapy mask", "red light mask"),
            categoryLabel = "LED light mask",
            whatItIs = "A mask of LEDs that shine specific light wavelengths onto the skin.",
            goodFor = listOf("Red light is studied for a calmer, firmer look", "Blue light is studied for blemish-prone skin"),
            fitsWho = listOf("Most skin types", "Those wanting a no-downtime device"),
            usage = "On clean, bare skin for the time in the manual, a few sessions a week. Consistency matters.",
            absorption = "Light reaches the skin without breaking it; results are gradual and depend on consistent use.",
            safety = listOf("Use the supplied eye protection", "Avoid if you take photosensitising medication", "Don't overuse beyond the manual"),
            verify = listOf("Follow the session times", "Manage expectations — effects are subtle and slow"),
        ),
        device(
            aliases = listOf("derma roller", "dermaroller", "microneedle", "microneedling roller"),
            categoryLabel = "Derma roller (microneedling)",
            whatItIs = "A roller of tiny needles that create micro-channels to prompt skin renewal.",
            goodFor = listOf("Texture and scarring (longer needles, professionally)", "At-home rollers are very short and mainly aid product absorption"),
            fitsWho = listOf("Healthy, non-active-acne skin", "Not over breakouts or inflamed skin"),
            usage = "On clean skin, gently, then a simple soothing routine after. Disinfect before and after every use.",
            absorption = "Micro-channels can let products penetrate deeper — which also raises irritation risk.",
            safety = listOf("Never roll over active acne, eczema or broken skin", "Sterilise the roller each time", "Avoid layering strong actives right after"),
            dontCombine = listOf("Retinol, vitamin C and acids immediately after rolling"),
            verify = listOf("Disinfect every use", "Replace worn rollers", "Keep needle length sensible at home"),
        ),
        device(
            aliases = listOf("gua sha"),
            categoryLabel = "Gua sha tool",
            whatItIs = "A flat stone tool used to massage the face and aid lymphatic flow.",
            goodFor = listOf("Relaxing facial tension", "Temporarily de-puffing", "A relaxing ritual"),
            fitsWho = listOf("Most people", "Avoid over active breakouts"),
            usage = "Over a facial oil, with light upward and outward strokes. A few minutes, regularly.",
            absorption = "Works mechanically on the surface and circulation; effects are temporary.",
            safety = listOf("Use a slip layer (oil) so you don't drag skin", "Go gentle — don't bruise", "Avoid over inflamed acne"),
            verify = listOf("Always use oil for slip", "Keep pressure light"),
        ),
        device(
            aliases = listOf("jade roller", "rose quartz roller"),
            categoryLabel = "Jade / quartz roller",
            whatItIs = "A rolling stone tool used to massage and cool the face.",
            goodFor = listOf("Temporarily de-puffing", "A calming massage", "Helping press in products"),
            fitsWho = listOf("Most people"),
            usage = "Roll gently outward over serum or oil. Keep it in the fridge for a cooling effect.",
            absorption = "Surface massage and cooling; benefits are temporary.",
            safety = listOf("Keep it clean", "Light pressure only"),
        ),
        device(
            aliases = listOf("ice roller", "face roller", "facial roller"),
            categoryLabel = "Ice / face roller",
            whatItIs = "A chilled roller used to cool and temporarily tighten the look of skin.",
            goodFor = listOf("Temporarily reducing puffiness", "Calming and refreshing"),
            fitsWho = listOf("Most people", "Soothing after actives or in the morning"),
            usage = "Roll gently over clean skin for a minute or two, especially mornings.",
            absorption = "Cold constricts surface vessels for a short-lived tightening look.",
            safety = listOf("Don't press hard or hold ice on one spot", "Keep it hygienic"),
        ),
        device(
            aliases = listOf("facial steamer", "face steamer", "steamer"),
            categoryLabel = "Facial steamer",
            whatItIs = "A device that produces warm steam to soften skin before cleansing.",
            goodFor = listOf("Softening skin and grime before a cleanse", "A relaxing ritual"),
            fitsWho = listOf("Most skin types", "Rosacea-prone skin should be cautious with heat"),
            usage = "A few minutes at a safe distance, before cleansing. Once or twice a week.",
            absorption = "Warmth and moisture soften the surface; it does not 'open pores'.",
            safety = listOf("Keep a safe distance to avoid burns", "Heat can flare redness/rosacea", "Use clean water"),
            verify = listOf("Keep sessions short", "Mind the distance"),
        ),
        device(
            aliases = listOf("cleansing brush", "facial cleansing brush", "sonic brush"),
            categoryLabel = "Cleansing brush",
            whatItIs = "A motorised brush that adds mechanical action to cleansing.",
            goodFor = listOf("A deeper-feeling cleanse"),
            fitsWho = listOf("Resilient skin", "Sensitive or acne-prone skin should be cautious"),
            usage = "With a gentle cleanser, briefly, a few times a week — not daily for most.",
            absorption = "Mechanical exfoliation on the surface; easy to overdo.",
            safety = listOf("Over-use can irritate and damage the barrier", "Keep the head clean to avoid bacteria"),
            verify = listOf("Replace heads regularly", "Don't over-scrub"),
        ),
        device(
            aliases = listOf("microcurrent", "microcurrent device"),
            categoryLabel = "Microcurrent device",
            whatItIs = "A handheld device that sends a low-level current to stimulate facial muscles.",
            goodFor = listOf("A temporary toned, lifted look with regular use"),
            fitsWho = listOf("Most people", "Avoid with certain medical/electrical implants"),
            usage = "Over the supplied conductive gel, following the device's routine, regularly.",
            absorption = "Stimulates muscle tone at the surface; effects fade without consistent use.",
            safety = listOf("Avoid with a pacemaker or other implanted electrical device", "Avoid in pregnancy unless cleared", "Use the conductive gel"),
            verify = listOf("Check contraindications in the manual", "Consistency is required"),
        ),
        device(
            aliases = listOf("high frequency", "high frequency wand"),
            categoryLabel = "High-frequency wand",
            whatItIs = "A device with a glass electrode marketed for blemish-prone skin.",
            goodFor = listOf("Marketed for blemish-prone skin"),
            fitsWho = listOf("Those targeting breakouts", "Avoid with certain medical devices"),
            usage = "On clean, dry skin per the manual, short sessions.",
            absorption = "Works at the surface; evidence at home is limited.",
            safety = listOf("Avoid with a pacemaker or pregnancy unless cleared", "Keep away from the eyes", "Don't use with flammable products nearby"),
            verify = listOf("Read the contraindications carefully"),
        ),
        device(
            aliases = listOf("pore vacuum", "blackhead remover", "blackhead vacuum"),
            categoryLabel = "Pore vacuum",
            whatItIs = "A suction device marketed to clear pores and blackheads.",
            goodFor = listOf("Marketed for blackheads"),
            fitsWho = listOf("Use cautiously", "Not for sensitive or rosacea-prone skin"),
            usage = "On softened skin, on the lowest setting, keeping it moving. Briefly.",
            absorption = "Mechanical suction at the surface.",
            safety = listOf("Can easily cause bruising and broken capillaries", "Never hold it still on one spot", "Avoid on inflamed or rosacea skin"),
            verify = listOf("Lowest setting", "Keep it moving"),
        ),
        device(
            aliases = listOf("skin scrubber", "spatula", "ultrasonic scrubber"),
            categoryLabel = "Ultrasonic skin scrubber",
            whatItIs = "A vibrating spatula marketed to lift debris from the skin surface.",
            goodFor = listOf("A gentle surface exfoliation feel"),
            fitsWho = listOf("Most skin types", "Go gentle if sensitive"),
            usage = "On damp skin, gliding gently, a couple of times a week.",
            absorption = "Surface-level; effects are mild.",
            safety = listOf("Don't over-use", "Keep pressure light"),
        ),
        device(
            aliases = listOf("scalp massager", "scalp brush"),
            categoryLabel = "Scalp massager",
            whatItIs = "A brush or tool to massage the scalp during or between washes.",
            goodFor = listOf("Relaxing scalp massage", "Helping lift buildup while shampooing"),
            fitsWho = listOf("Most people"),
            usage = "Use gently while shampooing or on a dry scalp; avoid scratching.",
            absorption = "Mechanical; improves the wash, not a growth treatment by itself.",
            safety = listOf("Be gentle to avoid irritating the scalp"),
        ),
    )

    // ====================================================================== //
    //  HAIRCARE — ~12 common products                                        //
    // ====================================================================== //
    private val HAIRCARE = listOf(
        haircare(
            aliases = listOf("minoxidil", "rogaine"),
            categoryLabel = "Minoxidil",
            whatItIs = "A topical treatment widely used to support hair regrowth.",
            goodFor = listOf("Pattern hair thinning", "Supporting regrowth with consistent use"),
            fitsWho = listOf("Those with thinning hair", "Needs ongoing use — stopping reverses gains"),
            usage = "Apply to a dry scalp as directed (commonly once or twice daily). Results take months and require consistency.",
            routineStep = "On a dry scalp, once or twice daily — leave in",
            absorption = "Absorbed at the scalp; benefits depend entirely on continued daily use.",
            safety = listOf("Can cause scalp dryness, itching or unwanted facial hair", "An initial shed is common before regrowth", "Avoid in pregnancy unless cleared"),
            verify = listOf("Commit to consistent daily use", "Give it several months", "Check the strength on the label"),
        ),
        haircare(
            aliases = listOf("finasteride"),
            categoryLabel = "Finasteride",
            whatItIs = "A treatment for male pattern hair loss, usually a prescription.",
            goodFor = listOf("Slowing male pattern hair loss"),
            fitsWho = listOf("Used under medical guidance", "Not for women who are or may become pregnant"),
            usage = "Use exactly as prescribed.",
            absorption = "Works systemically on the hormone pathway behind pattern loss.",
            safety = listOf("Prescription item — discuss side effects with a clinician", "Pregnant women should not handle broken tablets"),
            verify = listOf("Use only under medical guidance"),
        ),
        haircare(
            aliases = listOf("ketoconazole shampoo", "ketoconazole", "anti-dandruff shampoo", "antidandruff"),
            categoryLabel = "Ketoconazole / anti-dandruff shampoo",
            whatItIs = "A medicated shampoo for dandruff and flaky, itchy scalps.",
            goodFor = listOf("Dandruff and seborrhoeic flaking", "Itchy, flaky scalp"),
            fitsWho = listOf("Flaky or itchy scalps"),
            usage = "Lather and leave on the scalp for a few minutes before rinsing, a couple of times a week.",
            absorption = "Acts on the scalp's surface yeast/flaking; needs contact time to work.",
            safety = listOf("Can dry hair with overuse", "Patch test if your scalp is reactive"),
            verify = listOf("Leave on for the contact time", "Don't overuse"),
        ),
        haircare(
            aliases = listOf("clarifying shampoo", "sulfate shampoo", "sulphate shampoo"),
            categoryLabel = "Clarifying shampoo",
            whatItIs = "A stronger shampoo that strips buildup of product, oil and minerals.",
            goodFor = listOf("Removing heavy buildup", "Resetting weighed-down hair"),
            fitsWho = listOf("Anyone with product buildup", "Use occasionally, not daily"),
            usage = "Use occasionally (e.g. weekly or less); follow with conditioner as it can be drying.",
            absorption = "Strong surfactants strip the hair — effective but harsh if overused.",
            safety = listOf("Drying with frequent use", "Hard on coloured or dry hair"),
            verify = listOf("Use sparingly", "Always condition after"),
        ),
        haircare(
            aliases = listOf("sulfate-free shampoo", "sulphate-free shampoo", "gentle shampoo"),
            categoryLabel = "Sulfate-free shampoo",
            whatItIs = "A milder daily shampoo that cleans without harsh stripping.",
            goodFor = listOf("Gentle everyday cleansing", "Coloured, curly or dry hair"),
            fitsWho = listOf("Dry, curly or colour-treated hair"),
            usage = "Use as your regular shampoo; lather and rinse.",
            absorption = "Milder surfactants clean while preserving more natural oils.",
            safety = listOf("May need a clarifying wash occasionally to clear buildup"),
        ),
        haircare(
            aliases = listOf("dry shampoo"),
            categoryLabel = "Dry shampoo",
            whatItIs = "A spray or powder that absorbs oil to refresh hair between washes.",
            goodFor = listOf("Refreshing roots between washes", "Adding volume"),
            fitsWho = listOf("Most hair types"),
            usage = "Spray at the roots, wait, then brush through. Don't rely on it for days on end.",
            absorption = "Absorbs surface oil; it doesn't actually clean the scalp.",
            safety = listOf("Overuse can leave buildup on the scalp — wash properly regularly"),
            verify = listOf("Wash properly between uses"),
        ),
        haircare(
            aliases = listOf("hair oil", "argan oil", "coconut oil", "onion oil", "hair oiling"),
            categoryLabel = "Hair oil",
            whatItIs = "An oil used to condition, smooth and protect hair lengths.",
            goodFor = listOf("Smoothing frizz", "Conditioning dry ends", "Pre-wash treatment to reduce wash damage"),
            fitsWho = listOf("Dry, frizzy or coarse hair", "Use lightly on fine hair"),
            usage = "Pre-wash on lengths and ends, or a small amount on dry ends to finish. Avoid heavy oil on the scalp if you're prone to buildup.",
            routineStep = "Pre-wash on lengths/ends, or a little on dry ends to finish",
            absorption = "Coats and softens the hair shaft; some oils penetrate to reduce wash-day swelling.",
            safety = listOf("Heavy oiling can weigh down fine hair", "Wash out fully to avoid scalp buildup"),
        ),
        haircare(
            aliases = listOf("rosemary oil", "rosemary"),
            categoryLabel = "Rosemary oil (scalp)",
            whatItIs = "A botanical oil popular for scalp massage and marketed for thinning hair.",
            goodFor = listOf("Marketed for scalp circulation and thinning hair"),
            fitsWho = listOf("Those exploring gentle, natural options"),
            usage = "Dilute in a carrier oil, massage into the scalp, leave on then wash out. Patch test first.",
            absorption = "Applied to the scalp; evidence is early and limited.",
            safety = listOf("Always dilute essential oil before scalp use", "Patch test for irritation"),
            verify = listOf("Dilute properly", "Manage expectations — evidence is limited"),
        ),
        haircare(
            aliases = listOf("leave-in conditioner", "leave in conditioner", "leave-in"),
            categoryLabel = "Leave-in conditioner",
            whatItIs = "A lightweight conditioner left in to detangle and protect hair.",
            goodFor = listOf("Detangling", "Ongoing moisture", "Heat and frizz protection"),
            fitsWho = listOf("Dry, curly or damaged hair"),
            usage = "Apply to damp lengths after washing; don't rinse. Daily as needed.",
            routineStep = "After washing, on damp lengths — before styling; leave in",
            absorption = "Coats the shaft to smooth and protect through the day.",
            safety = listOf("Use lightly on fine hair to avoid greasiness"),
        ),
        haircare(
            aliases = listOf("hair conditioner", "conditioner", "deep conditioner", "hair mask"),
            categoryLabel = "Conditioner / hair mask",
            whatItIs = "A rinse-out treatment that softens, detangles and repairs the look of hair.",
            goodFor = listOf("Softness and detangling", "Repairing the look of damage (masks)"),
            fitsWho = listOf("All hair types", "Masks suit dry or damaged hair"),
            usage = "After shampoo, on lengths and ends (not the scalp), rinse after a few minutes. Masks weekly.",
            routineStep = "After shampoo, on lengths and ends; rinse out",
            absorption = "Smooths the cuticle to reduce frizz and breakage.",
            safety = listOf("Keep off the scalp if you're prone to buildup"),
        ),
        haircare(
            aliases = listOf("hair serum", "hair growth serum", "redensyl", "anti-frizz serum"),
            categoryLabel = "Hair serum",
            whatItIs = "A leave-in serum for smoothing the hair or, for scalp serums, targeting thinning.",
            goodFor = listOf("Smoothing and shine (length serums)", "Supporting thinning hair (scalp serums)"),
            fitsWho = listOf("Depends on the type — length vs scalp"),
            usage = "Length serums: a few drops on damp/dry ends. Scalp serums: apply to the scalp as directed, consistently.",
            absorption = "Length serums coat the shaft; scalp serums need consistent use to show anything.",
            safety = listOf("Patch test scalp serums", "Check the active ingredients"),
            verify = listOf("Confirm whether it's for the length or the scalp"),
        ),
        haircare(
            aliases = listOf("scalp serum", "scalp scrub", "scalp tonic", "hair tonic"),
            categoryLabel = "Scalp treatment",
            whatItIs = "A leave-on or wash-off treatment aimed at scalp health.",
            goodFor = listOf("Soothing or exfoliating the scalp", "Supporting a healthier scalp environment"),
            fitsWho = listOf("Flaky, oily or itchy scalps"),
            usage = "Apply to the scalp as directed; scrubs are used before shampoo, serums are usually left on.",
            absorption = "Works at the scalp; results need consistent use.",
            safety = listOf("Patch test", "Don't over-exfoliate the scalp"),
        ),
    )

    // ====================================================================== //
    //  FUNCTIONAL FOODS — ~12 common items                                   //
    // ====================================================================== //
    private val FOODS = listOf(
        food(
            aliases = listOf("apple cider vinegar", "acv"),
            categoryLabel = "Apple cider vinegar",
            whatItIs = "A fermented vinegar taken diluted for digestion and blood-sugar interest.",
            goodFor = listOf("Often used around meals for blood-sugar interest", "A tangy fermented food"),
            fitsWho = listOf("Most people in small, diluted amounts"),
            usage = "Always dilute in water; many take a small amount before a carb-heavy meal. Don't drink it neat.",
            absorption = "Its acidity is the active part; effects on blood sugar are modest.",
            safety = listOf("Acidic — can erode tooth enamel and irritate the throat if undiluted", "Rinse the mouth after", "Caution with reflux"),
            verify = listOf("Always dilute", "Don't overdo the amount"),
        ),
        food(
            aliases = listOf("green tea", "matcha"),
            categoryLabel = "Green tea / matcha",
            whatItIs = "A tea rich in antioxidants and a moderate source of caffeine.",
            goodFor = listOf("Antioxidants (catechins)", "Gentle, steady caffeine with L-theanine for calm focus"),
            fitsWho = listOf("Most people", "Sensitive-to-caffeine people should mind the timing"),
            usage = "Drink through the day; avoid late if caffeine affects your sleep. Don't take with iron-rich meals if iron absorption matters.",
            absorption = "Catechins and caffeine are well absorbed; tannins can reduce iron uptake from the same meal.",
            safety = listOf("Contains caffeine", "Tannins can lower non-heme iron absorption"),
            dontCombine = listOf("Iron supplements at the same time (separate by a couple of hours)"),
            verify = listOf("Mind caffeine timing", "Separate from iron"),
        ),
        food(
            aliases = listOf("kefir"),
            categoryLabel = "Kefir",
            whatItIs = "A fermented milk drink rich in live cultures.",
            goodFor = listOf("Gut-flora support from live cultures", "Protein and calcium"),
            fitsWho = listOf("Most people", "Dairy kefir isn't suitable if you avoid dairy"),
            usage = "A small daily serving; start small if you're new to fermented foods.",
            absorption = "Live cultures act in the gut; effects vary by person and product.",
            safety = listOf("Introduce gradually to avoid bloating", "Contains dairy unless it's a water/coconut version"),
        ),
        food(
            aliases = listOf("kombucha"),
            categoryLabel = "Kombucha",
            whatItIs = "A fermented tea with live cultures and a tangy taste.",
            goodFor = listOf("A fermented source of live cultures", "A lower-sugar fizzy-drink swap"),
            fitsWho = listOf("Most people", "Start small if sensitive"),
            usage = "A small daily serving; watch the sugar content on sweeter brands.",
            absorption = "Fermentation by-products act in the gut; effects are individual.",
            safety = listOf("Contains a trace of alcohol and some caffeine", "Can be acidic and sugary"),
        ),
        food(
            aliases = listOf("kimchi", "sauerkraut", "fermented vegetables"),
            categoryLabel = "Kimchi / sauerkraut",
            whatItIs = "Fermented vegetables rich in fibre and live cultures.",
            goodFor = listOf("Gut-flora support", "Fibre and flavour"),
            fitsWho = listOf("Most people", "Those watching sodium should mind portions"),
            usage = "A small daily portion as a side; introduce gradually.",
            absorption = "Live cultures and fibre act in the gut.",
            safety = listOf("High in salt", "Introduce slowly to avoid bloating"),
        ),
        food(
            aliases = listOf("yogurt", "yoghurt", "greek yogurt", "curd"),
            categoryLabel = "Yogurt",
            whatItIs = "A cultured dairy food with live cultures, protein and calcium.",
            goodFor = listOf("Gut-flora support (live cultures)", "Protein and calcium"),
            fitsWho = listOf("Most people", "Choose unsweetened; not for those avoiding dairy"),
            usage = "A daily serving; pick plain/unsweetened and look for live cultures.",
            absorption = "Live cultures act in the gut; nutrients are well absorbed.",
            safety = listOf("Contains dairy", "Flavoured versions can be high in sugar"),
        ),
        food(
            aliases = listOf("psyllium husk", "psyllium", "isabgol", "ispaghula"),
            categoryLabel = "Psyllium husk",
            whatItIs = "A soluble fibre that supports digestive regularity and fullness.",
            goodFor = listOf("Digestive regularity", "Feeling fuller", "Supporting healthy cholesterol as part of diet"),
            fitsWho = listOf("Most people wanting more fibre"),
            usage = "Mix into a full glass of water and drink promptly; increase fluids. Start with a small amount.",
            absorption = "Forms a gel in the gut; needs plenty of water to work and avoid blockage.",
            safety = listOf("Always take with lots of water", "Can reduce absorption of medicines taken at the same time"),
            dontCombine = listOf("Taking it at the exact same time as medications (separate by a couple of hours)"),
            verify = listOf("Drink plenty of water", "Separate from medicines"),
        ),
        food(
            aliases = listOf("chia seeds", "chia"),
            categoryLabel = "Chia seeds",
            whatItIs = "Tiny seeds rich in fibre and plant omega-3 (ALA).",
            goodFor = listOf("Fibre", "Plant omega-3 (ALA)", "Feeling fuller"),
            fitsWho = listOf("Most people"),
            usage = "Soak in liquid or stir into food; drink enough water alongside.",
            absorption = "Swell with water to a gel; plant omega-3 converts only partly to the active forms.",
            safety = listOf("Always eat with enough liquid — dry seeds can swell uncomfortably"),
        ),
        food(
            aliases = listOf("flaxseed", "flax seed", "linseed"),
            categoryLabel = "Flaxseed",
            whatItIs = "A seed high in fibre, lignans and plant omega-3 (ALA).",
            goodFor = listOf("Fibre", "Plant omega-3 (ALA)", "Lignans"),
            fitsWho = listOf("Most people"),
            usage = "Use ground (not whole) for absorption; stir into food. Keep ground flax cool.",
            absorption = "Whole seeds pass through largely undigested — grind them first.",
            safety = listOf("Drink enough water with added fibre"),
            verify = listOf("Use ground, not whole"),
        ),
        food(
            aliases = listOf("oats", "oatmeal", "rolled oats"),
            categoryLabel = "Oats",
            whatItIs = "A whole grain high in beta-glucan, a soluble fibre.",
            goodFor = listOf("Soluble fibre (beta-glucan)", "Steady energy", "Supporting healthy cholesterol as part of diet"),
            fitsWho = listOf("Most people", "Choose certified gluten-free if you need it"),
            usage = "A daily breakfast or snack base; less processed (rolled/steel-cut) is gentler on blood sugar.",
            absorption = "Beta-glucan slows digestion for steadier energy and fullness.",
            safety = listOf("Generally very well tolerated"),
        ),
        food(
            aliases = listOf("honey", "raw honey", "manuka"),
            categoryLabel = "Honey",
            whatItIs = "A natural sweetener with some soothing properties.",
            goodFor = listOf("Soothing a sore throat or cough", "A natural sweetener"),
            fitsWho = listOf("Most people over one year old"),
            usage = "Use in small amounts; it still counts as sugar.",
            absorption = "Absorbed like other sugars.",
            safety = listOf("Never give honey to infants under one year", "Still a sugar — use sparingly"),
        ),
        food(
            aliases = listOf("ginger", "ginger shot", "ginger tea"),
            categoryLabel = "Ginger",
            whatItIs = "A root used to ease nausea and add warming flavour.",
            goodFor = listOf("Easing nausea", "Digestive comfort", "Warming flavour"),
            fitsWho = listOf("Most people"),
            usage = "Fresh, as tea, or a small shot; use moderate amounts.",
            absorption = "Active compounds act on the digestive system.",
            safety = listOf("Large amounts can cause heartburn", "Caution with blood thinners at high intakes"),
        ),
        food(
            aliases = listOf("bone broth"),
            categoryLabel = "Bone broth",
            whatItIs = "A simmered broth marketed for collagen, minerals and gut comfort.",
            goodFor = listOf("A warming, protein-containing drink", "Hydration with some minerals"),
            fitsWho = listOf("Most people"),
            usage = "A warm daily cup as part of meals.",
            absorption = "Provides amino acids and minerals; specific 'collagen' claims are overstated.",
            safety = listOf("Can be high in sodium depending on preparation"),
            verify = listOf("Treat strong collagen/gut claims as marketing"),
        ),
    )

    private val ALL: List<Curated> = SKINCARE + DEVICES + HAIRCARE + FOODS

    private val normalized: List<Pair<String, Curated>> by lazy {
        ALL.flatMap { c ->
            (listOf(c.profile.categoryLabel) + c.aliases).map { norm(it) to c }
        }.sortedByDescending { it.first.length } // prefer the most specific alias
    }

    private fun norm(s: String): String =
        s.lowercase().replace(Regex("[^a-z0-9]+"), " ").trim()

    /**
     * Best-effort match of a product/item name to a curated non-supplement profile,
     * or null. Mirrors [IngredientCatalog.match]: exact alias first, then longest-alias
     * containment. When [kindHint] is given, a match must agree with it so e.g. a "hair
     * oil" isn't served a skincare-oil profile.
     */
    fun match(name: String, kindHint: ItemKind? = null): CategoryProfile? {
        val n = norm(name)
        if (n.isBlank()) return null
        fun ok(c: Curated) = kindHint == null || kindHint == ItemKind.OTHER || c.profile.kind == kindHint
        // exact alias first, then containment (longest alias wins via the sort).
        normalized.firstOrNull { it.first == n && ok(it.second) }?.let { return it.second.profile }
        return normalized.firstOrNull { n.contains(it.first) && it.first.length >= 3 && ok(it.second) }?.second?.profile
    }
}
