package com.quietdose.brain.analysis

import com.quietdose.data.model.DoseUnit
import com.quietdose.data.model.ItemFlags

/**
 * A curated, authoritative knowledge base of well-established supplement
 * ingredients — the *validated facts* the [StackAnalyzer] grounds its reasoning
 * in. Encoded conservatively from common, undisputed references; hedged by
 * construction and never medical advice. The on-device model (when present)
 * reasons OVER these facts; it never invents doses or interactions.
 *
 * Cross-references in [Ingredient.pairsWith]/[Ingredient.avoidWith] use [Ingredient.key].
 */
object IngredientCatalog {

    private fun f(vararg flags: Int): Int = flags.fold(0) { a, b -> a or b }

    val ALL: List<Ingredient> = listOf(
        Ingredient(
            key = "vitamin_d3", displayName = "Vitamin D3", category = "Vitamins",
            aliases = listOf("vitamin d", "d3", "cholecalciferol", "vit d"),
            benefits = listOf("Bone and immune support", "Works with K2 for calcium handling"),
            typicalDoseLow = 1000.0, typicalDoseHigh = 4000.0, doseUnit = DoseUnit.IU,
            timingFlags = f(ItemFlags.FAT_SOLUBLE, ItemFlags.WITH_FOOD),
            pairsWith = listOf("vitamin_k2", "magnesium"),
            evidenceNote = "Well established; absorbed best with dietary fat.",
            cautions = listOf("Very high doses build up over time — fat-soluble.", "Best dosed to a blood level, not guessed."),
            upperLimitDose = 4000.0,
            contraindications = listOf("Caution with high blood calcium, kidney stones, or sarcoidosis."),
            sideEffects = listOf("rare at normal doses"),
            tier = 1,
        ),
        Ingredient(
            key = "vitamin_k2", displayName = "Vitamin K2", category = "Vitamins",
            aliases = listOf("k2", "menaquinone", "mk-7", "mk7"),
            benefits = listOf("Directs calcium to bone", "Commonly paired with D3"),
            typicalDoseLow = 90.0, typicalDoseHigh = 200.0, doseUnit = DoseUnit.MCG,
            timingFlags = f(ItemFlags.FAT_SOLUBLE, ItemFlags.WITH_FOOD),
            pairsWith = listOf("vitamin_d3"),
            evidenceNote = "Fat-soluble; typically taken alongside D3.",
            drugInteractions = listOf("warfarin and other blood thinners"),
            tier = 1,
        ),
        Ingredient(
            key = "iron", displayName = "Iron (bisglycinate)", category = "Minerals",
            aliases = listOf("iron", "ferrous", "bisglycinate", "iron bisglycinate"),
            benefits = listOf("Supports healthy iron levels", "Better absorbed with vitamin C"),
            typicalDoseLow = 18.0, typicalDoseHigh = 65.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.EMPTY_STOMACH, ItemFlags.AVOID_CAFFEINE, ItemFlags.AVOID_CALCIUM),
            pairsWith = listOf("vitamin_c"),
            avoidWith = listOf("calcium", "magnesium", "zinc"),
            evidenceNote = "Absorption drops with tea/coffee and calcium; vitamin C helps.",
            cautions = listOf("Don't supplement iron without knowing your levels — excess is harmful.", "Can upset the stomach; bisglycinate is gentler."),
            upperLimitDose = 45.0,
            contraindications = listOf("Avoid with haemochromatosis or iron overload.", "Keep well away from children — overdose is dangerous."),
            sideEffects = listOf("constipation", "nausea", "dark stools"),
            tier = 1,
        ),
        Ingredient(
            key = "vitamin_c", displayName = "Vitamin C", category = "Vitamins",
            aliases = listOf("vitamin c", "ascorbic", "ascorbate", "vit c"),
            benefits = listOf("Antioxidant", "Enhances non-heme iron absorption"),
            typicalDoseLow = 250.0, typicalDoseHigh = 1000.0, doseUnit = DoseUnit.MG,
            pairsWith = listOf("iron"),
            evidenceNote = "Commonly taken with iron to aid absorption.",
            upperLimitDose = 2000.0,
            sideEffects = listOf("loose stools or stomach upset above ~1000 mg"),
            tier = 1,
        ),
        Ingredient(
            key = "calcium", displayName = "Calcium", category = "Minerals",
            aliases = listOf("calcium", "ca citrate", "calcium carbonate"),
            benefits = listOf("Bone support"),
            typicalDoseLow = 500.0, typicalDoseHigh = 1000.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            avoidWith = listOf("iron", "zinc", "magnesium"),
            evidenceNote = "Competes with iron, zinc and magnesium for absorption — separate them.",
            upperLimitDose = 2500.0,
            sideEffects = listOf("constipation", "bloating"),
            tier = 1,
        ),
        Ingredient(
            key = "magnesium", displayName = "Magnesium", category = "Minerals",
            aliases = listOf("magnesium", "mag", "glycinate", "mag glycinate", "mag7", "bisglycinate magnesium", "citrate magnesium"),
            benefits = listOf("Muscle and nervous-system support", "Often taken in the evening"),
            typicalDoseLow = 200.0, typicalDoseHigh = 400.0, doseUnit = DoseUnit.MG,
            pairsWith = listOf("vitamin_d3"),
            avoidWith = listOf("calcium", "iron"),
            evidenceNote = "Commonly taken at night; separate from calcium and iron.",
            upperLimitDose = 350.0,
            contraindications = listOf("Lower the dose with reduced kidney function."),
            sideEffects = listOf("loose stools (especially the oxide/citrate forms)"),
            drugInteractions = listOf("some antibiotics and thyroid medication (separate by a few hours)"),
            tier = 1,
        ),
        Ingredient(
            key = "zinc", displayName = "Zinc", category = "Minerals",
            aliases = listOf("zinc", "zinc picolinate", "zinc citrate"),
            benefits = listOf("Immune support"),
            typicalDoseLow = 15.0, typicalDoseHigh = 30.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            pairsWith = listOf("copper"),
            avoidWith = listOf("calcium", "iron"),
            evidenceNote = "Long-term high zinc can lower copper — many pair the two.",
            cautions = listOf("Sustained high doses deplete copper.", "On an empty stomach it can cause nausea."),
            upperLimitDose = 40.0,
            sideEffects = listOf("nausea on an empty stomach"),
            tier = 1,
        ),
        Ingredient(
            key = "copper", displayName = "Copper", category = "Minerals",
            aliases = listOf("copper", "copper bisglycinate"),
            benefits = listOf("Balances zinc intake"),
            typicalDoseLow = 1.0, typicalDoseHigh = 2.0, doseUnit = DoseUnit.MG,
            pairsWith = listOf("zinc"),
            evidenceNote = "Often added to offset higher zinc intake.", tier = 2,
        ),
        Ingredient(
            key = "omega3", displayName = "Omega-3 (fish oil)", category = "Omega",
            aliases = listOf("omega", "omega 3", "omega-3", "fish oil", "epa", "dha"),
            benefits = listOf("Heart and brain support"),
            typicalDoseLow = 1000.0, typicalDoseHigh = 2000.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.FAT_SOLUBLE, ItemFlags.WITH_FOOD),
            evidenceNote = "Taken with a meal to aid absorption and reduce reflux.",
            drugInteractions = listOf("blood thinners (additive effect at high doses)"),
            contraindications = listOf("Pause before planned surgery."),
            sideEffects = listOf("fishy aftertaste", "mild reflux"),
            tier = 1,
        ),
        Ingredient(
            key = "selenium", displayName = "Selenium", category = "Minerals",
            aliases = listOf("selenium", "selenomethionine"),
            benefits = listOf("Antioxidant; thyroid support"),
            typicalDoseLow = 100.0, typicalDoseHigh = 200.0, doseUnit = DoseUnit.MCG,
            evidenceNote = "A narrow range — more is not better.",
            cautions = listOf("Toxic in excess — easy to overdo with multivitamins.", "Often already covered by diet/multis."),
            upperLimitDose = 400.0,
            sideEffects = listOf("garlic breath, hair/nail changes only at toxic intakes"),
            tier = 2,
        ),
        Ingredient(
            key = "folate", displayName = "L-Methylfolate", category = "Vitamins",
            aliases = listOf("folate", "methylfolate", "l-methylfolate", "5-mthf", "folic"),
            benefits = listOf("Methylation support", "Paired with B12"),
            typicalDoseLow = 400.0, typicalDoseHigh = 1000.0, doseUnit = DoseUnit.MCG,
            pairsWith = listOf("b12"),
            evidenceNote = "Commonly taken together with B12.",
            upperLimitDose = 1000.0,
            cautions = listOf("High folate can mask a B12 deficiency — keep them paired."),
            tier = 1,
        ),
        Ingredient(
            key = "b12", displayName = "Methyl-B12", category = "Vitamins",
            aliases = listOf("b12", "methylcobalamin", "cobalamin", "vitamin b12"),
            benefits = listOf("Energy metabolism; nerve support", "Paired with folate"),
            typicalDoseLow = 500.0, typicalDoseHigh = 2000.0, doseUnit = DoseUnit.MCG,
            pairsWith = listOf("folate"),
            evidenceNote = "Often co-located with folate.", tier = 1,
        ),
        Ingredient(
            key = "glycine", displayName = "Glycine", category = "Sleep",
            aliases = listOf("glycine"),
            benefits = listOf("Calming; sleep quality"),
            typicalDoseLow = 3000.0, typicalDoseHigh = 5000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Commonly taken before bed.", tier = 2,
        ),
        Ingredient(
            key = "nac", displayName = "NAC", category = "Actives",
            aliases = listOf("nac", "n-acetyl", "acetylcysteine", "cysteine"),
            benefits = listOf("Glutathione precursor; antioxidant"),
            typicalDoseLow = 600.0, typicalDoseHigh = 1200.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Supportive evidence across several areas.", tier = 2,
        ),
        Ingredient(
            key = "melatonin", displayName = "Melatonin", category = "Sleep",
            aliases = listOf("melatonin"),
            benefits = listOf("Sleep-onset support"),
            typicalDoseLow = 0.5, typicalDoseHigh = 3.0, doseUnit = DoseUnit.MG,
            avoidWith = listOf("caffeine"),
            evidenceNote = "Low doses near bedtime are commonly noted; more isn't better.",
            cautions = listOf("Higher doses can cause grogginess; 0.5–1 mg is often enough.", "Best occasional, not a nightly crutch."),
            contraindications = listOf("Don't drive or operate machinery after taking it."),
            sideEffects = listOf("morning grogginess", "vivid dreams", "headache"),
            tier = 1,
        ),
        Ingredient(
            key = "creatine", displayName = "Creatine", category = "Actives",
            aliases = listOf("creatine", "monohydrate"),
            benefits = listOf("Strength and recovery", "Cognitive support"),
            typicalDoseLow = 3000.0, typicalDoseHigh = 5000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Among the most well-studied supplements; daily timing is flexible.", tier = 1,
        ),
        Ingredient(
            key = "nmn", displayName = "NMN", category = "Longevity",
            aliases = listOf("nmn", "nicotinamide mononucleotide"),
            benefits = listOf("NAD+ precursor"),
            typicalDoseLow = 250.0, typicalDoseHigh = 500.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.FASTED),
            evidenceNote = "Emerging human evidence; often taken in the morning.", tier = 3,
        ),
        Ingredient(
            key = "ca_akg", displayName = "Ca-AKG", category = "Longevity",
            aliases = listOf("ca-akg", "akg", "alpha-ketoglutarate", "calcium akg"),
            benefits = listOf("Cellular-aging research interest"),
            typicalDoseLow = 1000.0, typicalDoseHigh = 2000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Early evidence; popular in longevity stacks.", tier = 3,
        ),
        Ingredient(
            key = "spermidine", displayName = "Spermidine", category = "Longevity",
            aliases = listOf("spermidine"),
            benefits = listOf("Autophagy research interest"),
            typicalDoseLow = 1.0, typicalDoseHigh = 6.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Emerging; commonly taken in the morning.", tier = 3,
        ),
        Ingredient(
            key = "urolithin_a", displayName = "Urolithin A", category = "Longevity",
            aliases = listOf("urolithin", "urolithin a", "mitopure"),
            benefits = listOf("Mitochondrial (mitophagy) support"),
            typicalDoseLow = 500.0, typicalDoseHigh = 1000.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Growing human data; taken with a meal.", tier = 2,
        ),
        Ingredient(
            key = "curcumin", displayName = "Curcumin", category = "Actives",
            aliases = listOf("curcumin", "turmeric"),
            benefits = listOf("Antioxidant; joint comfort"),
            typicalDoseLow = 500.0, typicalDoseHigh = 1000.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.FAT_SOLUBLE, ItemFlags.WITH_FOOD),
            evidenceNote = "Absorption improves with fat and piperine.",
            drugInteractions = listOf("blood thinners (with high-dose extracts)"),
            sideEffects = listOf("mild stomach upset"),
            tier = 2,
        ),
        Ingredient(
            key = "coq10", displayName = "CoQ10", category = "Actives",
            aliases = listOf("coq10", "coenzyme q10", "ubiquinol", "ubiquinone"),
            benefits = listOf("Cellular energy; heart support"),
            typicalDoseLow = 100.0, typicalDoseHigh = 200.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.FAT_SOLUBLE, ItemFlags.WITH_FOOD),
            evidenceNote = "Fat-soluble; taken with a meal.",
            drugInteractions = listOf("warfarin (may reduce its effect)"),
            tier = 2,
        ),
        Ingredient(
            key = "ashwagandha", displayName = "Ashwagandha", category = "Actives",
            aliases = listOf("ashwagandha", "ksm-66", "withania"),
            benefits = listOf("Stress and sleep support"),
            typicalDoseLow = 300.0, typicalDoseHigh = 600.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Reasonable evidence for stress; often taken in the evening.",
            cautions = listOf("Often cycled, not taken indefinitely."),
            contraindications = listOf("Avoid in pregnancy.", "Caution with thyroid conditions or autoimmune disease.", "Pause before planned surgery."),
            drugInteractions = listOf("thyroid medication, sedatives, and immunosuppressants"),
            sideEffects = listOf("drowsiness", "stomach upset"),
            tier = 2,
        ),
        Ingredient(
            key = "berberine", displayName = "Berberine", category = "Actives",
            aliases = listOf("berberine"),
            benefits = listOf("Metabolic / glucose support"),
            typicalDoseLow = 500.0, typicalDoseHigh = 1500.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Taken with meals, usually split through the day.",
            cautions = listOf("Commonly causes GI upset."),
            contraindications = listOf("Avoid in pregnancy and breastfeeding."),
            drugInteractions = listOf("metformin and other glucose-lowering drugs", "blood-pressure medication", "cyclosporine"),
            sideEffects = listOf("cramping", "diarrhoea", "constipation"),
            tier = 2,
        ),
        Ingredient(
            key = "taurine", displayName = "Taurine", category = "Actives",
            aliases = listOf("taurine"),
            benefits = listOf("Cardiovascular and exercise interest"),
            typicalDoseLow = 1000.0, typicalDoseHigh = 3000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Active research area; well tolerated.", tier = 3,
        ),
        Ingredient(
            key = "collagen", displayName = "Collagen", category = "Actives",
            aliases = listOf("collagen", "peptides"),
            benefits = listOf("Skin, hair and joint support"),
            typicalDoseLow = 10.0, typicalDoseHigh = 20.0, doseUnit = DoseUnit.G,
            evidenceNote = "Commonly taken as a daily powder.", tier = 2,
        ),
        Ingredient(
            key = "vitamin_b_complex", displayName = "B-complex", category = "Vitamins",
            aliases = listOf("b complex", "b-complex", "vitamin b"),
            benefits = listOf("Energy metabolism (B vitamins)"),
            typicalDoseLow = 1.0, typicalDoseHigh = 1.0, doseUnit = DoseUnit.UNIT,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Usually taken earlier in the day.", tier = 2,
        ),
        Ingredient(
            key = "probiotics", displayName = "Probiotics", category = "Actives",
            aliases = listOf("probiotic", "probiotics", "lactobacillus", "bifidobacterium"),
            benefits = listOf("Gut-flora support"),
            typicalDoseLow = 1.0, typicalDoseHigh = 1.0, doseUnit = DoseUnit.UNIT,
            evidenceNote = "Strain-specific; effects vary by product.", tier = 2,
        ),

        // --- Starter expansion batch (well-established, conservatively encoded) ---
        Ingredient(
            key = "vitamin_a", displayName = "Vitamin A", category = "Vitamins",
            aliases = listOf("vitamin a", "retinyl", "retinol palmitate", "retinyl palmitate", "vit a"),
            benefits = listOf("Vision and skin support", "Immune support"),
            typicalDoseLow = 700.0, typicalDoseHigh = 900.0, doseUnit = DoseUnit.MCG,
            timingFlags = f(ItemFlags.FAT_SOLUBLE, ItemFlags.WITH_FOOD),
            evidenceNote = "Fat-soluble; preformed vitamin A builds up over time.",
            cautions = listOf("Easy to overdo with liver, multis and fortified foods combined."),
            upperLimitDose = 3000.0,
            contraindications = listOf("Avoid high preformed-A doses in pregnancy."),
            tier = 1,
        ),
        Ingredient(
            key = "vitamin_e", displayName = "Vitamin E", category = "Vitamins",
            aliases = listOf("vitamin e", "tocopherol", "alpha-tocopherol", "vit e"),
            benefits = listOf("Antioxidant", "Protects cell membranes"),
            typicalDoseLow = 15.0, typicalDoseHigh = 67.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.FAT_SOLUBLE, ItemFlags.WITH_FOOD),
            evidenceNote = "Fat-soluble; absorbed best with a meal.",
            upperLimitDose = 1000.0,
            drugInteractions = listOf("blood thinners (additive at high doses)"),
            tier = 2,
        ),
        Ingredient(
            key = "vitamin_b6", displayName = "Vitamin B6", category = "Vitamins",
            aliases = listOf("b6", "vitamin b6", "pyridoxine", "p5p", "pyridoxal"),
            benefits = listOf("Amino-acid metabolism", "Nervous-system support"),
            typicalDoseLow = 1.3, typicalDoseHigh = 25.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Water-soluble; usually taken with food.",
            cautions = listOf("Sustained high doses can affect nerves — stay well under the limit."),
            upperLimitDose = 100.0,
            tier = 1,
        ),
        Ingredient(
            key = "vitamin_b1", displayName = "Vitamin B1 (thiamine)", category = "Vitamins",
            aliases = listOf("b1", "thiamine", "thiamin", "vitamin b1", "benfotiamine"),
            benefits = listOf("Energy metabolism", "Nerve support"),
            typicalDoseLow = 1.1, typicalDoseHigh = 100.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Water-soluble; well tolerated.", tier = 2,
        ),
        Ingredient(
            key = "biotin", displayName = "Biotin", category = "Vitamins",
            aliases = listOf("biotin", "vitamin b7", "b7", "vitamin h"),
            benefits = listOf("Hair, skin and nail support"),
            typicalDoseLow = 30.0, typicalDoseHigh = 100.0, doseUnit = DoseUnit.MCG,
            evidenceNote = "Widely supplemented; deficiency is uncommon.",
            cautions = listOf("High-dose biotin can skew some lab tests — tell your clinician."),
            tier = 2,
        ),
        Ingredient(
            key = "potassium", displayName = "Potassium", category = "Minerals",
            aliases = listOf("potassium", "potassium citrate", "potassium chloride"),
            benefits = listOf("Fluid balance and nerve function"),
            typicalDoseLow = 99.0, typicalDoseHigh = 99.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Best from food; supplement doses are kept low for safety.",
            cautions = listOf("Don't take extra potassium without guidance."),
            contraindications = listOf("Caution with kidney disease or potassium-affecting medication."),
            drugInteractions = listOf("ACE inhibitors, ARBs and potassium-sparing diuretics"),
            tier = 1,
        ),
        Ingredient(
            key = "iodine", displayName = "Iodine", category = "Minerals",
            aliases = listOf("iodine", "potassium iodide", "kelp"),
            benefits = listOf("Thyroid-hormone support"),
            typicalDoseLow = 150.0, typicalDoseHigh = 150.0, doseUnit = DoseUnit.MCG,
            evidenceNote = "A narrow range — both too little and too much affect the thyroid.",
            cautions = listOf("Excess iodine can disrupt thyroid function."),
            upperLimitDose = 1100.0,
            contraindications = listOf("Caution with thyroid conditions."),
            tier = 1,
        ),
        Ingredient(
            key = "chromium", displayName = "Chromium", category = "Minerals",
            aliases = listOf("chromium", "chromium picolinate"),
            benefits = listOf("Glucose-metabolism interest"),
            typicalDoseLow = 200.0, typicalDoseHigh = 200.0, doseUnit = DoseUnit.MCG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Mixed evidence; effects are modest at best.", tier = 3,
        ),
        Ingredient(
            key = "boron", displayName = "Boron", category = "Minerals",
            aliases = listOf("boron"),
            benefits = listOf("Bone and hormone research interest"),
            typicalDoseLow = 3.0, typicalDoseHigh = 6.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Trace mineral; small doses studied.", tier = 3,
        ),
        Ingredient(
            key = "l_theanine", displayName = "L-Theanine", category = "Actives",
            aliases = listOf("theanine", "l-theanine", "l theanine"),
            benefits = listOf("Calm focus", "Often paired with caffeine"),
            typicalDoseLow = 100.0, typicalDoseHigh = 200.0, doseUnit = DoseUnit.MG,
            pairsWith = listOf("caffeine"),
            evidenceNote = "Commonly paired with caffeine to smooth its edge.", tier = 2,
        ),
        Ingredient(
            key = "caffeine", displayName = "Caffeine", category = "Actives",
            aliases = listOf("caffeine", "caffeine anhydrous"),
            benefits = listOf("Alertness and focus", "Exercise performance"),
            typicalDoseLow = 100.0, typicalDoseHigh = 200.0, doseUnit = DoseUnit.MG,
            pairsWith = listOf("l_theanine"),
            avoidWith = listOf("melatonin"),
            evidenceNote = "Well studied; effect and tolerance vary widely.",
            cautions = listOf("Avoid late in the day so it doesn't disturb sleep."),
            upperLimitDose = 400.0,
            contraindications = listOf("Caution with anxiety, heart rhythm issues, or in pregnancy."),
            sideEffects = listOf("jitteriness", "raised heart rate", "disturbed sleep"),
            tier = 1,
        ),
        Ingredient(
            key = "rhodiola", displayName = "Rhodiola rosea", category = "Actives",
            aliases = listOf("rhodiola", "rhodiola rosea", "golden root"),
            benefits = listOf("Stress and fatigue support"),
            typicalDoseLow = 200.0, typicalDoseHigh = 400.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.FASTED),
            evidenceNote = "Adaptogen; often taken earlier in the day.",
            cautions = listOf("Can feel stimulating — avoid late in the day."),
            tier = 2,
        ),
        Ingredient(
            key = "lions_mane", displayName = "Lion's Mane", category = "Actives",
            aliases = listOf("lions mane", "lion's mane", "hericium"),
            benefits = listOf("Cognitive and nerve research interest"),
            typicalDoseLow = 500.0, typicalDoseHigh = 1000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Emerging human data; well tolerated.", tier = 3,
        ),
        Ingredient(
            key = "ginkgo", displayName = "Ginkgo biloba", category = "Actives",
            aliases = listOf("ginkgo", "ginkgo biloba"),
            benefits = listOf("Circulation and memory interest"),
            typicalDoseLow = 120.0, typicalDoseHigh = 240.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Mixed evidence; standardised extracts studied.",
            drugInteractions = listOf("blood thinners"),
            contraindications = listOf("Pause before planned surgery."),
            tier = 3,
        ),
        Ingredient(
            key = "milk_thistle", displayName = "Milk Thistle", category = "Actives",
            aliases = listOf("milk thistle", "silymarin"),
            benefits = listOf("Liver-support research interest"),
            typicalDoseLow = 200.0, typicalDoseHigh = 400.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Silymarin is the studied fraction; evidence is mixed.", tier = 3,
        ),
        Ingredient(
            key = "saw_palmetto", displayName = "Saw Palmetto", category = "Actives",
            aliases = listOf("saw palmetto", "serenoa"),
            benefits = listOf("Prostate and hair research interest"),
            typicalDoseLow = 160.0, typicalDoseHigh = 320.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Mixed evidence; commonly taken with food.", tier = 3,
        ),
        Ingredient(
            key = "quercetin", displayName = "Quercetin", category = "Actives",
            aliases = listOf("quercetin"),
            benefits = listOf("Antioxidant; immune research interest"),
            typicalDoseLow = 500.0, typicalDoseHigh = 1000.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Often paired with vitamin C; absorption is modest.", tier = 3,
        ),
        Ingredient(
            key = "resveratrol", displayName = "Resveratrol", category = "Longevity",
            aliases = listOf("resveratrol", "trans-resveratrol"),
            benefits = listOf("Antioxidant; longevity research interest"),
            typicalDoseLow = 150.0, typicalDoseHigh = 500.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.FAT_SOLUBLE, ItemFlags.WITH_FOOD),
            evidenceNote = "Fat-soluble; human evidence is still emerging.", tier = 3,
        ),
        Ingredient(
            key = "nr", displayName = "Nicotinamide Riboside", category = "Longevity",
            aliases = listOf("nicotinamide riboside", "niagen", "nr"),
            benefits = listOf("NAD+ precursor"),
            typicalDoseLow = 250.0, typicalDoseHigh = 500.0, doseUnit = DoseUnit.MG,
            evidenceNote = "NAD+ precursor; emerging human evidence.", tier = 3,
        ),
        Ingredient(
            key = "pqq", displayName = "PQQ", category = "Longevity",
            aliases = listOf("pqq", "pyrroloquinoline"),
            benefits = listOf("Mitochondrial research interest"),
            typicalDoseLow = 10.0, typicalDoseHigh = 20.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Early evidence; often paired with CoQ10.", tier = 3,
        ),
        Ingredient(
            key = "alpha_lipoic_acid", displayName = "Alpha-Lipoic Acid", category = "Actives",
            aliases = listOf("alpha lipoic acid", "alpha-lipoic", "ala", "lipoic acid"),
            benefits = listOf("Antioxidant; glucose-metabolism interest"),
            typicalDoseLow = 300.0, typicalDoseHigh = 600.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.EMPTY_STOMACH),
            evidenceNote = "Often taken away from meals.", tier = 3,
        ),
        Ingredient(
            key = "l_carnitine", displayName = "L-Carnitine", category = "Actives",
            aliases = listOf("carnitine", "l-carnitine", "acetyl-l-carnitine", "alcar"),
            benefits = listOf("Fat metabolism and exercise interest"),
            typicalDoseLow = 500.0, typicalDoseHigh = 2000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Several forms; effects are modest.", tier = 3,
        ),
        Ingredient(
            key = "l_glutamine", displayName = "L-Glutamine", category = "Actives",
            aliases = listOf("glutamine", "l-glutamine"),
            benefits = listOf("Gut and recovery research interest"),
            typicalDoseLow = 5000.0, typicalDoseHigh = 10000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Commonly taken as a daily powder.", tier = 3,
        ),
        Ingredient(
            key = "beta_alanine", displayName = "Beta-Alanine", category = "Actives",
            aliases = listOf("beta alanine", "beta-alanine"),
            benefits = listOf("Muscular endurance"),
            typicalDoseLow = 3000.0, typicalDoseHigh = 5000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Well studied for endurance; can cause harmless tingling.",
            sideEffects = listOf("tingling (paresthesia)"),
            tier = 2,
        ),
        Ingredient(
            key = "citrulline", displayName = "L-Citrulline", category = "Actives",
            aliases = listOf("citrulline", "l-citrulline", "citrulline malate"),
            benefits = listOf("Blood flow and exercise performance"),
            typicalDoseLow = 3000.0, typicalDoseHigh = 8000.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.EMPTY_STOMACH),
            evidenceNote = "Often taken before exercise.", tier = 2,
        ),
        Ingredient(
            key = "glucosamine", displayName = "Glucosamine", category = "Actives",
            aliases = listOf("glucosamine", "glucosamine sulfate", "glucosamine sulphate"),
            benefits = listOf("Joint-comfort research interest"),
            typicalDoseLow = 1500.0, typicalDoseHigh = 1500.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            pairsWith = listOf("chondroitin"),
            evidenceNote = "Mixed evidence; often paired with chondroitin.", tier = 3,
        ),
        Ingredient(
            key = "chondroitin", displayName = "Chondroitin", category = "Actives",
            aliases = listOf("chondroitin", "chondroitin sulfate", "chondroitin sulphate"),
            benefits = listOf("Joint-comfort research interest"),
            typicalDoseLow = 800.0, typicalDoseHigh = 1200.0, doseUnit = DoseUnit.MG,
            pairsWith = listOf("glucosamine"),
            evidenceNote = "Commonly combined with glucosamine.", tier = 3,
        ),
        Ingredient(
            key = "psyllium", displayName = "Psyllium husk", category = "Actives",
            aliases = listOf("psyllium", "psyllium husk", "isabgol", "ispaghula"),
            benefits = listOf("Soluble fibre; digestive regularity"),
            typicalDoseLow = 5.0, typicalDoseHigh = 10.0, doseUnit = DoseUnit.G,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Take with plenty of water; separate from medicines.",
            cautions = listOf("Take with a full glass of water.", "Can reduce absorption of medicines taken at the same time."),
            tier = 1,
        ),
        Ingredient(
            key = "inositol", displayName = "Inositol", category = "Actives",
            aliases = listOf("inositol", "myo-inositol", "myo inositol"),
            benefits = listOf("Mood and metabolic research interest"),
            typicalDoseLow = 2000.0, typicalDoseHigh = 4000.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Studied in higher daily amounts; well tolerated.", tier = 3,
        ),
        Ingredient(
            key = "5htp", displayName = "5-HTP", category = "Sleep",
            aliases = listOf("5-htp", "5htp", "griffonia"),
            benefits = listOf("Mood and sleep research interest"),
            typicalDoseLow = 50.0, typicalDoseHigh = 200.0, doseUnit = DoseUnit.MG,
            evidenceNote = "Often taken in the evening.",
            contraindications = listOf("Don't combine with antidepressants without medical advice."),
            drugInteractions = listOf("SSRIs and other serotonergic medication"),
            tier = 3,
        ),
        Ingredient(
            key = "vitamin_b3", displayName = "Niacin (B3)", category = "Vitamins",
            aliases = listOf("niacin", "vitamin b3", "b3", "nicotinic acid", "nicotinamide", "niacinamide supplement"),
            benefits = listOf("Energy metabolism"),
            typicalDoseLow = 14.0, typicalDoseHigh = 16.0, doseUnit = DoseUnit.MG,
            timingFlags = f(ItemFlags.WITH_FOOD),
            evidenceNote = "Higher-dose niacin can cause flushing.",
            cautions = listOf("Nicotinic-acid forms can cause harmless flushing."),
            upperLimitDose = 35.0,
            tier = 2,
        ),
    )

    private val normalized: List<Pair<String, Ingredient>> by lazy {
        ALL.flatMap { ing ->
            (listOf(ing.displayName, ing.key) + ing.aliases).map { norm(it) to ing }
        }.sortedByDescending { it.first.length } // prefer the most specific alias
    }

    private fun norm(s: String): String =
        s.lowercase().replace(Regex("[^a-z0-9]+"), " ").trim()

    /** Best-effort match of a product/item name to a known ingredient, or null. */
    fun match(name: String): Ingredient? {
        val n = norm(name)
        if (n.isBlank()) return null
        // exact alias first, then containment (longest alias wins via the sort).
        normalized.firstOrNull { it.first == n }?.let { return it.second }
        return normalized.firstOrNull { n.contains(it.first) && it.first.length >= 3 }?.second
    }

    fun byKey(key: String): Ingredient? = ALL.firstOrNull { it.key == key }
}
