package com.quietdose.brain.analysis

import org.json.JSONObject

/**
 * A small, persistable description of a product's drawn "look" — enough to redraw the
 * same glyph later (e.g. in the stack list) without re-sampling the packaging photo.
 * It's derived from the SLM output (container form) + the colours sampled off the real
 * packaging, and it's editable, so the icon can be regenerated by changing this spec.
 * Everything is optional: an empty/absent field means "fall back to deriving it".
 */
data class ProductLook(
    val form: String = "",          // ContainerForm name, e.g. "DROPPER_BOTTLE"; empty → infer from the item
    val bodyArgb: Long? = null,     // sampled body colour as ARGB; null → category fallback palette
    val accentArgb: Long? = null,   // sampled cap/accent colour as ARGB
    val initials: String = "",      // monogram override; empty → derive from brand/name
)

/** Serialise a [ProductLook] to/from a compact JSON blob for the item row. Never throws. */
object ProductLookCodec {
    fun encode(l: ProductLook): String = JSONObject().apply {
        if (l.form.isNotBlank()) put("form", l.form)
        l.bodyArgb?.let { put("body", it) }
        l.accentArgb?.let { put("accent", it) }
        if (l.initials.isNotBlank()) put("initials", l.initials)
    }.toString()

    fun decode(s: String?): ProductLook? {
        if (s.isNullOrBlank()) return null
        return runCatching {
            val o = JSONObject(s)
            ProductLook(
                form = o.optString("form"),
                bodyArgb = if (o.has("body")) o.optLong("body") else null,
                accentArgb = if (o.has("accent")) o.optLong("accent") else null,
                initials = o.optString("initials"),
            )
        }.getOrNull()
    }
}
